In [1]:

#%matplotlib inline 

#Array processing
import numpy as np

#Data analysis, wrangling and common exploratory operations
import pandas as pd
from pandas import Series, DataFrame
from sklearn import preprocessing

#For visualization. Matplotlib for basic viz and seaborn for more stylish figures + statistical figures not in MPL.
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.display import Image
from pandas import read_csv
import warnings
warnings.filterwarnings(action="ignore")
import matplotlib
matplotlib.axes.Axes.pie
matplotlib.pyplot.pie
from sklearn.datasets import fetch_mldata, load_boston                                                                       
from sklearn.utils import shuffle                                                                                            
from sklearn.neighbors import KNeighborsClassifier                                                                           
from sklearn import metrics                                                                                                  
from sklearn import tree                                                                                                     
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor                                                       
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB                                                       
from sklearn.svm import SVC, LinearSVC , SVR                                                                                 
from sklearn.linear_model import Perceptron, LogisticRegression, LinearRegression                                            
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor                                                    
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier                                                       
from sklearn.cross_validation import KFold, train_test_split, cross_val_score                                                
from sklearn.preprocessing import StandardScaler
from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.ensemble import AdaBoostClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import RFECV
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectPercentile
from sklearn.preprocessing import Binarizer 
from sklearn.feature_selection import SelectFromModel

In [2]:
dt= pd.read_csv('C:/Users/User-PC/Desktop/usis29mar.csv')
print(dt.columns)

Index(['1st_choice', '2nd_choice', '3rd_choice', 'ssc_or_olevel',
       'hsc_or_alevel', 'medium', 'ssc_board', 'hsc_board',
       'registered_program'],
      dtype='object')

In [3]:
x = dt.drop('registered_program',1)

In [4]:

for col_name in x.columns:
    if x[col_name].dtypes == 'object':
        unique_cat = len(x[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} unique catagories".format(
             col_name=col_name, unique_cat= unique_cat))

todummy_list = ['1st_choice','2nd_choice','3rd_choice','medium','ssc_board','hsc_board']

Feature '1st_choice' has 16 unique catagories
Feature '2nd_choice' has 17 unique catagories
Feature '3rd_choice' has 17 unique catagories
Feature 'medium' has 4 unique catagories
Feature 'ssc_board' has 12 unique catagories
Feature 'hsc_board' has 12 unique catagories

In [5]:
# function to dummy all the cat var used for modeling
def dummy_dt(dt,todummy_list):
    for n in todummy_list:
        dummies = pd.get_dummies(dt[n], prefix=n,dummy_na=False)
        dt=dt.drop(n,1)
        dt=pd.concat([dt,dummies],axis=1)
    return dt

In [6]:
x = dummy_dt(x,todummy_list)
x.columns

Index(['ssc_or_olevel', 'hsc_or_alevel', '1st_choice_ANT-1',
       '1st_choice_APE-1', '1st_choice_ARC-1', '1st_choice_BBA-1',
       '1st_choice_BIO-1', '1st_choice_CS-1', '1st_choice_CSE-1',
       '1st_choice_ECE-1', '1st_choice_ECO-1', '1st_choice_EEE-1',
       '1st_choice_ENG-1', '1st_choice_LLB-1', '1st_choice_MAT-1',
       '1st_choice_MIC-1', '1st_choice_PHR-1', '1st_choice_PHY-1',
       '2nd_choice_ANT-2', '2nd_choice_APE-2', '2nd_choice_ARC-2',
       '2nd_choice_BBA-2', '2nd_choice_BIO-2', '2nd_choice_CS-2',
       '2nd_choice_CSE-2', '2nd_choice_ECE-2', '2nd_choice_ECO-2',
       '2nd_choice_EEE-2', '2nd_choice_ENG-2', '2nd_choice_LLB-2',
       '2nd_choice_MAT-2', '2nd_choice_MIC-2', '2nd_choice_PHR-2',
       '2nd_choice_PHY-2', '3rd_choice_ANT-3', '3rd_choice_APE-3',
       '3rd_choice_ARC-3', '3rd_choice_BBA-3', '3rd_choice_BIO-3',
       '3rd_choice_CS-3', '3rd_choice_CSE-3', '3rd_choice_ECE-3',
       '3rd_choice_ECO-3', '3rd_choice_EEE-3', '3rd_choice_ENG-3',
       '3rd_choice_LLB-3', '3rd_choice_MAT-3', '3rd_choice_MIC-3',
       '3rd_choice_PHR-3', '3rd_choice_PHY-3', 'medium_ban', 'medium_eng',
       'medium_eng-ver', 'medium_madrasah', 'ssc_board_Barisal',
       'ssc_board_CBSE', 'ssc_board_Chittagong', 'ssc_board_Comilla',
       'ssc_board_Dhaka', 'ssc_board_Dinajpur', 'ssc_board_Jessore',
       'ssc_board_Madrasah', 'ssc_board_Others', 'ssc_board_Rajshahi',
       'ssc_board_Sylhet', 'hsc_board_Barisal', 'hsc_board_CBSE',
       'hsc_board_Chittagong', 'hsc_board_Comilla', 'hsc_board_Dhaka',
       'hsc_board_Dinajpur', 'hsc_board_Jessore', 'hsc_board_Madrasah',
       'hsc_board_Others', 'hsc_board_Rajshahi', 'hsc_board_Sylhet'],
      dtype='object')

In [9]:
x.head(10)

,ssc_or_olevel,hsc_or_alevel,1st_choice_ANT-1,1st_choice_APE-1,1st_choice_ARC-1,1st_choice_BBA-1,1st_choice_BIO-1,1st_choice_CS-1,1st_choice_CSE-1,1st_choice_ECE-1,...,hsc_board_CBSE,hsc_board_Chittagong,hsc_board_Comilla,hsc_board_Dhaka,hsc_board_Dinajpur,hsc_board_Jessore,hsc_board_Madrasah,hsc_board_Others,hsc_board_Rajshahi,hsc_board_Sylhet
0,5.0,4.5,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,5.0,5.0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
2,5.0,4.8,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,NaN,4.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5.0,5.0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
5,5.0,5.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,5.0,5.0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
7,5.0,5.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,5.0,4.9,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
9,NaN,5.0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [8]:
map_obj_y=  { "registered_program":{"PHY" : 1,"ECO" : 2, "ANT" :3,"CSE":4, "ARC":5, "PHR":6,"BBA" : 7, "BIO":8,
               "LLB":9,"ENG":10,"MAT":11, "MIC":12,"APE":13,"ECE":14, "EEE":15, "CS":16}}
dt.replace(map_obj_y  ,inplace=True)
y = dt.registered_program
y.head()

0     6
1    13
2     6
3     9
4     7
Name: registered_program, dtype: int64

In [10]:
dt.isnull().sum().sort_values(ascending=False)

3rd_choice            1000
hsc_board              554
ssc_board              545
hsc_or_alevel          301
ssc_or_olevel          214
2nd_choice              53
registered_program       0
medium                   0
1st_choice               0
dtype: int64

In [11]:
#Impute missing values using Imputer in aklearn.preprocessing
# y doesn't have any NaN values in the dataset
from sklearn.preprocessing import Imputer

imp= Imputer(missing_values= 'NaN', strategy='median', axis=0) 
#median posses no issue cause ssc/olevel result is now in one col -
#manually and another feature "medium" was added manually
imp.fit(x)
x= pd.DataFrame(data=imp.transform(x),columns=x.columns)

#now check again for null if any
x.isnull().sum().sort_values(ascending=False).head(10) #x has 76 columns after binarizing

hsc_board_Sylhet    0
2nd_choice_EEE-2    0
2nd_choice_ARC-2    0
2nd_choice_BBA-2    0
2nd_choice_BIO-2    0
2nd_choice_CS-2     0
2nd_choice_CSE-2    0
2nd_choice_ECE-2    0
2nd_choice_ECO-2    0
2nd_choice_ENG-2    0
dtype: int64

In [12]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42, train_size=.70)

print(dt.shape)
print(x.shape)

(2277, 9)
(2277, 76)

In [14]:
#large set of feat can cause overfitting
# feature selection

import sklearn.feature_selection

select = sklearn.feature_selection.SelectKBest(k=30)
selected_features = select.fit(X_train, y_train)
indices_selected = selected_features.get_support(indices=True)
colnames_selected = [x.columns[i] for i in indices_selected]

X_train_selected = X_train[colnames_selected]
X_test_selected = X_test[colnames_selected]

In [15]:
colnames_selected

['1st_choice_ANT-1',
 '1st_choice_APE-1',
 '1st_choice_ARC-1',
 '1st_choice_BBA-1',
 '1st_choice_BIO-1',
 '1st_choice_CSE-1',
 '1st_choice_ECE-1',
 '1st_choice_ECO-1',
 '1st_choice_EEE-1',
 '1st_choice_ENG-1',
 '1st_choice_LLB-1',
 '1st_choice_MAT-1',
 '1st_choice_MIC-1',
 '1st_choice_PHR-1',
 '1st_choice_PHY-1',
 '2nd_choice_APE-2',
 '2nd_choice_BBA-2',
 '2nd_choice_BIO-2',
 '2nd_choice_ECE-2',
 '2nd_choice_ECO-2',
 '2nd_choice_EEE-2',
 '2nd_choice_ENG-2',
 '2nd_choice_LLB-2',
 '2nd_choice_MAT-2',
 '2nd_choice_MIC-2',
 '2nd_choice_PHY-2',
 '3rd_choice_ANT-3',
 '3rd_choice_APE-3',
 '3rd_choice_MIC-3',
 'medium_eng']

In [18]:
sizes=[]
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=.20)
names = ["KNN", "Logistic Regression","Linear SVM","Gaussian Process",
         "Decision Tree", "Random Forest", "Naive Bayes"]

classifiers = [
    KNeighborsClassifier(),
    LogisticRegression(),
    SVC(),
    GaussianProcessClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GaussianNB()
]

In [19]:
# iterate over classifiers
for name, clf in zip(names, classifiers):
    # ax = plt.subplot(len(datasets), len(classifiers) + 1, i)
    clf.fit(X_train,y_train)
    pred = clf.predict(X_test)
    score = accuracy_score(pred,y_test)
    print("-----",name,"-----")
    result = (score*100)
    sizes.append(result)
    print("Score: %.2f %%"%(score*100))
    print("\n\n")

----- KNN -----
Score: 54.61 %



----- Logistic Regression -----
Score: 64.91 %



----- Linear SVM -----
Score: 57.24 %



----- Gaussian Process -----
Score: 62.50 %



----- Decision Tree -----
Score: 54.82 %



----- Random Forest -----
Score: 59.87 %



----- Naive Bayes -----
Score: 22.81 %